spring.application.name=forum-api

spring.datasource.url=jdbc:mysql://localhost:3306/forum

# Credenciais do MySQL
spring.datasource.username=root
spring.datasource.password=

# Driver do MySQL (opcional nas versões mais recentes do Spring Boot)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
